apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-default
spec:
  acme:
    email: pablo.barrales@movelab.cl
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-default
    solvers:
      - http01:
          ingress:
            class: kong
