---
kind: pipeline
type: kubernetes
name: "Ngnix"

steps:
  - name: echo
    image: bash
    commands:
      - echo "Inicio pipeline"

  - name: build and publish
    image: plugins/gcr
    settings:
      repo: movelab-main/nginx
      tags:
        - latest
        - "${DRONE_COMMIT}"
      json_key:
        from_secret: google_credentials

  - name: deploy
    image: nytimes/drone-gke
    settings:
      cluster: gke-beta
      expand_env_vars: true
      namespace: nginx
      vars:
        replicas: 1
        appname: nginx
        build: "${DRONE_COMMIT}"
        consul_http_addr: consul.canary.movelab.cl
        consul_http_token: a6554a75-8fb9-d864-0661-b1ffd9eaab8a
      verbose: true
      zone: us-central1-a
    environment:
      TOKEN:
        from_secret: google_credentials
