apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.appname}}
  namespace: {{.namespace}}
  labels:
    app: {{.appname}}
spec:
  replicas: {{.replicas}}
  selector:
    matchLabels:
      app: {{.appname}}
  template:
    metadata:
      labels:
        app: {{.appname}}
    spec:
      containers:
        - name: {{.appname}}
          image: gcr.io/{{.project}}/nginx:latest
          ports:
            - containerPort: 80
